name: Shopify Theme Preview

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  manage-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        if: github.event.action != 'closed'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x" # Using LTS version for stability

      - name: Install Shopify CLI
        run: |
          npm install -g @shopify/cli @shopify/theme
          shopify version

      - name: Create .env file
        run: |
          echo "SHOPIFY_FLAG_STORE=${{ secrets.SHOPIFY_STORE }}" >> $GITHUB_ENV
          echo "SHOPIFY_CLI_THEME_TOKEN=${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}" >> $GITHUB_ENV

      - name: Authenticate with Shopify
        run: |
          echo "${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}" | shopify auth login --store "${{ secrets.SHOPIFY_STORE }}" --password
          shopify auth list

      - name: Push to Shopify and get preview URL
        id: push_theme
        if: github.event.action != 'closed'
        run: |
          output=$(shopify theme push --unpublished --store ${{ secrets.SHOPIFY_STORE }} --verbose --json || echo '{"error": true}')
          if echo "$output" | jq -e '.error' > /dev/null; then
            echo "Error pushing theme. Falling back to development theme."
            output=$(shopify theme info --store ${{ secrets.SHOPIFY_STORE }} --json)
          fi
          theme_id=$(echo "$output" | jq -r '.theme.id // empty')
          preview_url=$(echo "$output" | jq -r '.theme.preview_url // empty')
          if [ -z "$theme_id" ] || [ -z "$preview_url" ]; then
            echo "Failed to get theme information"
            exit 1
          fi
          echo "PREVIEW_URL=$preview_url" >> $GITHUB_OUTPUT
          echo "THEME_ID=$theme_id" >> $GITHUB_OUTPUT

      - name: Comment PR with preview link and theme ID
        if: github.event.action != 'closed'
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: `Preview link for this PR: ${{ steps.push_theme.outputs.PREVIEW_URL }}
              
              THEME_ID=${{ steps.push_theme.outputs.THEME_ID }}`
            })

      - name: Remove preview theme
        if: github.event.action == 'closed'
        run: |
          theme_id=$(curl -s ${{ github.event.pull_request.comments_url }} | jq -r '.[] | select(.body | contains("THEME_ID=")) | .body' | sed -n 's/.*THEME_ID=\([0-9]*\).*/\1/p' | tail -n1)
          if [ ! -z "$theme_id" ]; then
            shopify theme delete --store ${{ secrets.SHOPIFY_STORE }} -t $theme_id -f
          else
            echo "No theme ID found to delete"
          fi

      - name: Comment PR about removal
        if: github.event.action == 'closed'
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: 'The preview theme for this PR has been removed.'
            })
