name: Shopify Theme Preview

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  manage-preview:
    runs-on: ubuntu-latest
    steps:
      # ... (previous steps remain the same)

      - name: Create .env file
        run: |
          echo "SHOPIFY_FLAG_STORE=${{ secrets.SHOPIFY_STORE }}" >> $GITHUB_ENV
          echo "SHOPIFY_CLI_THEME_TOKEN=${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}" >> $GITHUB_ENV

      - name: Push to Shopify and get preview URL
        id: push_theme
        if: github.event.action != 'closed'
        run: |
          preview_url=$(shopify theme push --store ${{ secrets.SHOPIFY_STORE }} --json | jq -r '.previewUrl')
          theme_id=$(echo $preview_url | sed -n 's/.*preview_theme_id=\([0-9]*\).*/\1/p')
          echo "PREVIEW_URL=$preview_url" >> $GITHUB_OUTPUT
          echo "THEME_ID=$theme_id" >> $GITHUB_OUTPUT

      # ... (other steps remain the same)

      - name: Remove preview theme
        if: github.event.action == 'closed'
        run: |
          theme_id=$(cat $GITHUB_EVENT_PATH | jq -r '.pull_request.body' | sed -n 's/.*THEME_ID=\([0-9]*\).*/\1/p')
          if [ ! -z "$theme_id" ]; then
            shopify theme delete --store ${{ secrets.SHOPIFY_STORE }} -t $theme_id -f
          fi
